name: Ruby Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Check kernel version
      run: uname -r

    - name: Build Docker image
      run: docker build --progress=plain --no-cache -t ruby-test-project .

    - name: Verify Docker image
      run: |
        echo "Verifying Docker image details..."
        docker images ruby-test-project
        echo "Checking that git is not installed in container..."
        docker run --rm ruby-test-project sh -c "git --version || echo 'git is not installed (as expected)'"

    - name: Create test results directory
      run: mkdir -p test-results

    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/test-results:/tmp \
          -e DD_API_KEY="${{ secrets.DD_API_KEY }}" \
          -e DD_CIVISIBILITY_ENABLED=true \
          -e DD_SERVICE=ruby-test-project \
          -e DD_ENV=ci \
          -e DD_SITE=datadoghq.com \
          -e RUBYOPT="-rbundler/setup -rdatadog/ci/auto_instrument" \
          -e DD_CIVISIBILITY_AGENTLESS_ENABLED=true \
          -e DD_GIT_COMMIT_SHA=${{ github.sha }} \
          -e DD_GIT_BRANCH=${{ github.ref_name }} \
          -e DD_GIT_REPOSITORY_URL=${{ github.repositoryUrl }} \
          ruby-test-project

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/rspec.xml