name: Ruby Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        ruby-version: ['3.2.5']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Check kernel version
      run: uname -r

    - name: Install dependencies
      run: bundle install

    - name: Run tests with Datadog Test Optimization
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_SITE: ${{ secrets.DD_SITE || 'datadoghq.com' }}
        DD_ENV: ci
        DD_SERVICE: ruby-test-project
      run: bundle exec rspec